[workspace]
workspace.name = "Grafana CLI & Client Library"
workspace.version = "0.1.0"
workspace.edition = "2021"
workspace.description = "Sample usage of Grafana Client"
workspace.authors = ["Ryan Ruckley <rruckley@gmail.com>"]

members = [
    "grafana-lib",
    "grafana-cli",
]